services:
  mining_pool:
    build:
      context: ./mining_pool
      dockerfile: pool.Dockerfile
    container_name: mining_pool
    ports:
      - "8000:8000"
    networks:
      - mining_network
    environment:
      - SERVER_URL=mining_pool
    command:
      uvicorn server:app --host 0.0.0.0 --port 8000 --reload # only during development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http:/mining_pool:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  miner:
    build:
      context: ./miner
      dockerfile: miner.Dockerfile
    container_name: miner
    command:
      python -u miner.py
    environment:
      - SERVER_URL=${SERVER_URL}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    networks:
      - mining_network
    depends_on:
      mining_pool:
        condition: service_healthy

networks:
  mining_network:
    name: mining_pool
    driver: bridge
